/*
 * This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
 * This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).
 */

package io.twoyi;

import android.util.Log;

/**
 * Native server interface for the twoyi container.
 * 
 * This class provides JNI bindings to the Rust twoyi-server library,
 * allowing the container server to run directly in the app process
 * instead of as a separate executable.
 */
public class NativeServer {
    private static final String TAG = "NativeServer";
    private static boolean libraryLoaded = false;

    static {
        try {
            System.loadLibrary("twoyi_server");
            libraryLoaded = true;
            Log.i(TAG, "libtwoyi_server.so loaded successfully");
        } catch (UnsatisfiedLinkError e) {
            Log.e(TAG, "Failed to load libtwoyi_server.so: " + e.getMessage());
            libraryLoaded = false;
        }
    }

    /**
     * Check if the native library is available
     */
    public static boolean isLibraryLoaded() {
        return libraryLoaded;
    }

    /**
     * Initialize the native library (call once at app startup)
     */
    public static native void nativeInit();

    /**
     * Start the server with the given configuration
     * 
     * @param rootfs Path to the rootfs directory
     * @param loader Path to the loader library (or null)
     * @param bindAddress Address to bind for control connections (e.g., "0.0.0.0:8765")
     * @param adbAddress Address for ADB/scrcpy connections (e.g., "0.0.0.0:5556")
     * @param width Screen width
     * @param height Screen height
     * @param dpi Screen DPI
     * @param profile Profile name
     * @return true if server started successfully
     */
    public static native boolean startServer(
            String rootfs,
            String loader,
            String bindAddress,
            String adbAddress,
            int width,
            int height,
            int dpi,
            String profile
    );

    /**
     * Stop the server
     */
    public static native void stopServer();

    /**
     * Check if the server is running
     */
    public static native boolean isServerRunning();

    /**
     * Check if the container is running
     */
    public static native boolean isContainerRunning();

    /**
     * Start only the input system (for use with existing renderer)
     * 
     * @param rootfs Path to the rootfs directory
     * @param width Screen width
     * @param height Screen height
     */
    public static native void startInputSystem(String rootfs, int width, int height);

    /**
     * Handle a touch event
     * 
     * @param action Touch action (DOWN=0, UP=1, MOVE=2, etc.)
     * @param pointerId Pointer ID for multi-touch
     * @param x X coordinate
     * @param y Y coordinate
     * @param pressure Touch pressure (0-100)
     */
    public static native void handleTouchEvent(int action, int pointerId, int x, int y, int pressure);

    /**
     * Send a key event
     * 
     * @param keycode Android keycode
     */
    public static native void sendKeyCode(int keycode);

    /**
     * Start the server using default addresses
     * 
     * @param rootfs Path to the rootfs directory
     * @param loader Path to the loader library (or null)
     * @param width Screen width
     * @param height Screen height
     * @param dpi Screen DPI
     * @return true if server started successfully
     */
    public static boolean startServerDefault(String rootfs, String loader, int width, int height, int dpi) {
        return startServer(
                rootfs,
                loader,
                "0.0.0.0:8765",
                "0.0.0.0:5556",
                width,
                height,
                dpi,
                "default"
        );
    }
}
