/*
 * This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
 * This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).
 */

package io.twoyi;

import android.util.Log;

/**
 * JNI interface for libtwoyi.so
 * 
 * This class provides native methods to interact with the twoyi server.
 * The library (libtwoyi.so) works both as:
 * - A JNI library callable from Java
 * - A standalone executable server
 */
public class Twoyi {
    private static final String TAG = "Twoyi";
    private static boolean sLibraryLoaded = false;

    static {
        try {
            System.loadLibrary("twoyi");
            sLibraryLoaded = true;
            Log.i(TAG, "libtwoyi.so loaded successfully");
        } catch (UnsatisfiedLinkError e) {
            Log.e(TAG, "Failed to load libtwoyi.so", e);
            sLibraryLoaded = false;
        }
    }

    /**
     * Check if the native library is loaded
     */
    public static boolean isLibraryLoaded() {
        return sLibraryLoaded;
    }

    /**
     * Initialize the native library
     * @return true if initialization was successful
     */
    public static native boolean nativeInit();

    /**
     * Start the server in the background
     * @param rootfsPath Path to the rootfs directory
     * @param loaderPath Path to the loader library (can be null)
     * @param bindAddress Address and port to bind for control connections
     * @param width Screen width
     * @param height Screen height
     * @param dpi Screen DPI
     * @return true if server started successfully
     */
    public static native boolean nativeStartServer(
            String rootfsPath,
            String loaderPath,
            String bindAddress,
            int width,
            int height,
            int dpi
    );

    /**
     * Stop the running server
     * @return true if server was stopped
     */
    public static native boolean nativeStopServer();

    /**
     * Check if the server is currently running
     * @return true if server is running
     */
    public static native boolean nativeIsServerRunning();

    /**
     * Send a touch event to the container
     * @param action Touch action (ACTION_DOWN, ACTION_UP, ACTION_MOVE, etc.)
     * @param pointerId Pointer ID for multi-touch
     * @param x X coordinate
     * @param y Y coordinate
     * @param pressure Touch pressure (0-255)
     */
    public static native void nativeSendTouch(int action, int pointerId, int x, int y, int pressure);

    /**
     * Send a key event to the container
     * @param keycode Android keycode
     */
    public static native void nativeSendKey(int keycode);

    /**
     * Get the library version
     * @return Version string
     */
    public static native String nativeGetVersion();

    /**
     * Convenience method to start the server with default settings
     */
    public static boolean startServer(String rootfsPath, String loaderPath, int width, int height) {
        if (!sLibraryLoaded) {
            Log.e(TAG, "Cannot start server: library not loaded");
            return false;
        }
        return nativeStartServer(rootfsPath, loaderPath, "0.0.0.0:8765", width, height, 320);
    }

    /**
     * Convenience method to stop the server
     */
    public static boolean stopServer() {
        if (!sLibraryLoaded) {
            Log.e(TAG, "Cannot stop server: library not loaded");
            return false;
        }
        return nativeStopServer();
    }

    /**
     * Convenience method to check if server is running
     */
    public static boolean isServerRunning() {
        if (!sLibraryLoaded) {
            return false;
        }
        return nativeIsServerRunning();
    }

    /**
     * Convenience method to send a touch event
     */
    public static void sendTouch(int action, int pointerId, float x, float y, float pressure) {
        if (!sLibraryLoaded) {
            return;
        }
        nativeSendTouch(action, pointerId, (int) x, (int) y, (int) (pressure * 255));
    }

    /**
     * Convenience method to send a key event
     */
    public static void sendKey(int keycode) {
        if (!sLibraryLoaded) {
            return;
        }
        nativeSendKey(keycode);
    }
}
