/*
 * This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
 * This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).
 */

package io.twoyi.ui;

import android.app.AlertDialog;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.RadioButton;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.ActionBar;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import io.twoyi.R;
import io.twoyi.utils.Profile;
import io.twoyi.utils.ProfileManager;
import io.twoyi.utils.UIHelper;

/**
 * Activity for managing profiles (list, create, edit, delete)
 */
public class ProfileListActivity extends AppCompatActivity {

    private RecyclerView recyclerView;
    private ProfileAdapter adapter;
    private ProfileManager profileManager;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_profile_list);

        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.setDisplayHomeAsUpEnabled(true);
            actionBar.setTitle(R.string.profile_management_title);
        }

        profileManager = ProfileManager.getInstance(this);

        recyclerView = findViewById(R.id.profileRecyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        
        adapter = new ProfileAdapter();
        recyclerView.setAdapter(adapter);
        
        loadProfiles();
    }

    @Override
    protected void onResume() {
        super.onResume();
        loadProfiles();
    }

    private void loadProfiles() {
        List<Profile> profiles = profileManager.getProfilesSortedByLastUsed();
        String activeId = profileManager.getActiveProfile() != null ? 
                profileManager.getActiveProfile().getId() : null;
        adapter.setProfiles(profiles, activeId);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_profile_list, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            onBackPressed();
            return true;
        } else if (item.getItemId() == R.id.action_add_profile) {
            showCreateProfileDialog();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    private void showCreateProfileDialog() {
        EditText input = new EditText(this);
        input.setHint(R.string.profile_name_hint);
        input.setText(profileManager.generateUniqueName("Profile"));
        input.selectAll();

        new AlertDialog.Builder(this)
                .setTitle(R.string.create_profile_title)
                .setView(input)
                .setPositiveButton(android.R.string.ok, (dialog, which) -> {
                    String name = input.getText().toString().trim();
                    if (name.isEmpty()) {
                        Toast.makeText(this, R.string.profile_name_empty, Toast.LENGTH_SHORT).show();
                        return;
                    }
                    if (!profileManager.isNameUnique(name, null)) {
                        Toast.makeText(this, R.string.profile_name_exists, Toast.LENGTH_SHORT).show();
                        return;
                    }
                    Profile newProfile = new Profile(name);
                    profileManager.addProfile(newProfile);
                    loadProfiles();
                    
                    // Open edit screen for the new profile
                    openProfileEditor(newProfile.getId());
                })
                .setNegativeButton(android.R.string.cancel, null)
                .show();
    }

    private void openProfileEditor(String profileId) {
        Intent intent = new Intent(this, ProfileEditActivity.class);
        intent.putExtra(ProfileEditActivity.EXTRA_PROFILE_ID, profileId);
        startActivity(intent);
    }

    private void confirmDeleteProfile(Profile profile) {
        if (profileManager.getProfileCount() <= 1) {
            Toast.makeText(this, R.string.cannot_delete_last_profile, Toast.LENGTH_SHORT).show();
            return;
        }

        UIHelper.getDialogBuilder(this)
                .setTitle(R.string.delete_profile_title)
                .setMessage(getString(R.string.delete_profile_confirm, profile.getName()))
                .setPositiveButton(android.R.string.ok, (dialog, which) -> {
                    profileManager.deleteProfile(profile.getId());
                    loadProfiles();
                })
                .setNegativeButton(android.R.string.cancel, null)
                .show();
    }

    private void duplicateProfile(Profile profile) {
        Profile duplicate = profileManager.duplicateProfile(profile.getId());
        if (duplicate != null) {
            loadProfiles();
            Toast.makeText(this, R.string.profile_duplicated, Toast.LENGTH_SHORT).show();
        }
    }

    private void activateProfile(Profile profile) {
        profileManager.setActiveProfile(profile.getId());
        profile.updateLastUsed();
        profileManager.updateProfile(profile);
        loadProfiles();
        Toast.makeText(this, getString(R.string.profile_activated, profile.getName()), 
                Toast.LENGTH_SHORT).show();
    }

    private class ProfileAdapter extends RecyclerView.Adapter<ProfileAdapter.ViewHolder> {
        private List<Profile> profiles = new ArrayList<>();
        private String activeProfileId;

        void setProfiles(List<Profile> profiles, String activeProfileId) {
            this.profiles = profiles;
            this.activeProfileId = activeProfileId;
            notifyDataSetChanged();
        }

        @NonNull
        @Override
        public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            View view = LayoutInflater.from(parent.getContext())
                    .inflate(R.layout.item_profile, parent, false);
            return new ViewHolder(view);
        }

        @Override
        public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
            Profile profile = profiles.get(position);
            holder.bind(profile);
        }

        @Override
        public int getItemCount() {
            return profiles.size();
        }

        class ViewHolder extends RecyclerView.ViewHolder {
            private final RadioButton radioActive;
            private final TextView tvName;
            private final TextView tvMode;
            private final TextView tvLastUsed;
            private final ImageButton btnEdit;
            private final ImageButton btnMore;

            ViewHolder(@NonNull View itemView) {
                super(itemView);
                radioActive = itemView.findViewById(R.id.radioActive);
                tvName = itemView.findViewById(R.id.tvProfileName);
                tvMode = itemView.findViewById(R.id.tvProfileMode);
                tvLastUsed = itemView.findViewById(R.id.tvLastUsed);
                btnEdit = itemView.findViewById(R.id.btnEditProfile);
                btnMore = itemView.findViewById(R.id.btnMoreOptions);
            }

            void bind(Profile profile) {
                boolean isActive = profile.getId().equals(activeProfileId);
                
                radioActive.setChecked(isActive);
                tvName.setText(profile.getName());
                
                // Display mode
                String modeText = profile.isLegacyMode() ? 
                        getString(R.string.profile_mode_legacy) : 
                        getString(R.string.profile_mode_server);
                tvMode.setText(modeText);

                // Display last used time
                SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, HH:mm", Locale.getDefault());
                String lastUsed = getString(R.string.profile_last_used, 
                        sdf.format(new Date(profile.getLastUsedAt())));
                tvLastUsed.setText(lastUsed);

                // Click handlers
                radioActive.setOnClickListener(v -> {
                    if (!isActive) {
                        activateProfile(profile);
                    }
                });

                itemView.setOnClickListener(v -> {
                    if (!isActive) {
                        activateProfile(profile);
                    }
                });

                btnEdit.setOnClickListener(v -> openProfileEditor(profile.getId()));

                btnMore.setOnClickListener(v -> showProfileMenu(profile));
            }

            private void showProfileMenu(Profile profile) {
                android.widget.PopupMenu popup = new android.widget.PopupMenu(
                        ProfileListActivity.this, btnMore);
                popup.getMenuInflater().inflate(R.menu.menu_profile_item, popup.getMenu());
                
                popup.setOnMenuItemClickListener(item -> {
                    int id = item.getItemId();
                    if (id == R.id.action_duplicate) {
                        duplicateProfile(profile);
                        return true;
                    } else if (id == R.id.action_delete) {
                        confirmDeleteProfile(profile);
                        return true;
                    }
                    return false;
                });
                
                popup.show();
            }
        }
    }
}
