#!/bin/bash
# This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
# This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).

# Build twoyi as both:
# 1. libtwoyi.so - JNI library for Android app use
# 2. twoyi-server - standalone binary for CLI use

set -e

# Build the library and binary for Android arm64
# Arguments (e.g., --release) are passed from gradle
echo "Building twoyi for aarch64-linux-android..."
if ! cargo build --target aarch64-linux-android "$@"; then
    echo "Build failed!"
    exit 1
fi

# Determine the build profile from arguments
BUILD_PROFILE="debug"
for arg in "$@"; do
    if [ "$arg" = "--release" ]; then
        BUILD_PROFILE="release"
        break
    fi
done

# Copy libtwoyi.so to jniLibs for the Android app (app/rs is inside app/)
mkdir -p ../src/main/jniLibs/arm64-v8a
cp "target/aarch64-linux-android/${BUILD_PROFILE}/libtwoyi.so" ../src/main/jniLibs/arm64-v8a/libtwoyi.so || { echo "Copy libtwoyi.so failed!"; exit 1; }
echo "Copied libtwoyi.so to jniLibs/arm64-v8a/"

# Copy twoyi-server binary to assets for the app to execute as standalone
mkdir -p ../src/main/assets
cp "target/aarch64-linux-android/${BUILD_PROFILE}/twoyi-server" ../src/main/assets/twoyi-server || { echo "Copy twoyi-server failed!"; exit 1; }
echo "Copied twoyi-server to assets/"

echo ""
echo "Successfully built twoyi:"
echo "  - libtwoyi.so (JNI library)"
echo "  - twoyi-server (standalone binary)"
echo ""
echo "Usage: ./twoyi-server --help"
