#!/bin/bash
# This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
# This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).

# Build the server for Android arm64
# Usage: 
#   ./build_android.sh          # Build library (libtwoyi_server.so)
#   ./build_android.sh --cli    # Build CLI binary (twoyi-server)
#   ./build_android.sh --all    # Build both

BUILD_MODE="${1:---lib}"

# Build library (JNI)
build_lib() {
    echo "Building libtwoyi_server.so (JNI library)..."
    if ! cargo build --release --target aarch64-linux-android --lib --features jni; then
        echo "Library build failed!"
        exit 1
    fi
    
    # Copy to jniLibs directory
    mkdir -p ../app/src/main/jniLibs/arm64-v8a
    cp target/aarch64-linux-android/release/libtwoyi_server.so ../app/src/main/jniLibs/arm64-v8a/ || { echo "Copy failed!"; exit 1; }
    echo "Copied libtwoyi_server.so to jniLibs"
}

# Build CLI binary
build_cli() {
    echo "Building twoyi-server (CLI binary)..."
    if ! cargo build --release --target aarch64-linux-android --bin twoyi-server --features cli; then
        echo "CLI build failed!"
        exit 1
    fi
    
    # Copy to assets directory
    mkdir -p ../app/src/main/assets
    cp target/aarch64-linux-android/release/twoyi-server ../app/src/main/assets/twoyi-server || { echo "Copy failed!"; exit 1; }
    echo "Copied twoyi-server to assets"
}

case "$BUILD_MODE" in
    --lib)
        build_lib
        ;;
    --cli)
        build_cli
        ;;
    --all)
        build_lib
        build_cli
        ;;
    *)
        echo "Usage: $0 [--lib|--cli|--all]"
        echo "  --lib   Build JNI library (default)"
        echo "  --cli   Build CLI binary"
        echo "  --all   Build both"
        exit 1
        ;;
esac

echo "Build completed successfully!"
