#!/bin/bash
# This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
# This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).

# Build twoyi-server standalone binary for Android arm64
if ! cargo build --release --target aarch64-linux-android $1; then
    echo "Build failed!"
    exit 1
fi

# Copy twoyi-server binary to assets for the app to execute
mkdir -p ../app/src/main/assets
cp target/aarch64-linux-android/release/twoyi-server ../app/src/main/assets/twoyi-server || { echo "Copy binary failed!"; exit 1; }

echo "Successfully built and copied twoyi-server to assets/"
echo ""
echo "Usage: ./twoyi-server --help"
