#!/bin/bash
# This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
# This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).

# Build libtwoyi.so for Android arm64
# The resulting library works both as:
# 1. JNI library when loaded by Android app
# 2. Standalone executable when run from Termux: ./libtwoyi.so -r rootfs

echo "Building libtwoyi.so..."

if ! cargo build --release --target aarch64-linux-android; then
    echo "Build failed!"
    exit 1
fi

# Copy to jniLibs directory for Android app
mkdir -p ../app/src/main/jniLibs/arm64-v8a
cp target/aarch64-linux-android/release/libtwoyi.so ../app/src/main/jniLibs/arm64-v8a/ || { echo "Copy to jniLibs failed!"; exit 1; }
echo "Copied libtwoyi.so to jniLibs"

# Also copy to assets for Termux usage (users can extract and run directly)
mkdir -p ../app/src/main/assets
cp target/aarch64-linux-android/release/libtwoyi.so ../app/src/main/assets/ || { echo "Copy to assets failed!"; exit 1; }
echo "Copied libtwoyi.so to assets"

echo "Build completed successfully!"
echo ""
echo "Usage:"
echo "  In Android app: System.loadLibrary(\"twoyi\")"
echo "  In Termux: ./libtwoyi.so -r \$(realpath rootfs)"
