/*
 * This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
 * This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).
 */

package io.twoyi.utils;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Unit tests for Profile class
 */
public class ProfileTest {

    @Test
    public void testProfileCreation() {
        Profile profile = new Profile();
        assertNotNull(profile.getId());
        assertEquals("Default", profile.getName());
        assertEquals(Profile.MODE_LEGACY, profile.getMode());
        assertFalse(profile.isVerboseDebug());
        assertFalse(profile.isUse3rdPartyRom());
    }

    @Test
    public void testProfileCreationWithName() {
        Profile profile = new Profile("Test Profile");
        assertEquals("Test Profile", profile.getName());
    }

    @Test
    public void testProfileModeChecks() {
        Profile profile = new Profile();
        
        profile.setMode(Profile.MODE_LEGACY);
        assertTrue(profile.isLegacyMode());
        assertFalse(profile.isServerMode());
        
        profile.setMode(Profile.MODE_SERVER);
        assertFalse(profile.isLegacyMode());
        assertTrue(profile.isServerMode());
    }

    @Test
    public void testProfileAddresses() {
        Profile profile = new Profile();
        profile.setControlPort("8765");
        profile.setAdbPort("5556");
        
        assertEquals("127.0.0.1:8765", profile.getServerAddress());
        assertEquals("127.0.0.1:5556", profile.getAdbAddress());
    }

    // Note: Serialization test requires Android instrumentation test
    // because org.json.JSONObject is an Android class
    // See: ProfileInstrumentedTest for JSON serialization tests

    @Test
    public void testProfileEquality() {
        Profile profile1 = new Profile("Test1");
        Profile profile2 = new Profile("Test2");
        
        // Different IDs should not be equal
        assertNotEquals(profile1, profile2);
        
        // Same ID should be equal
        profile2.setId(profile1.getId());
        assertEquals(profile1, profile2);
    }

    @Test
    public void testUpdateLastUsed() {
        Profile profile = new Profile();
        long initialTime = profile.getLastUsedAt();
        
        // Set a specific past time
        profile.setLastUsedAt(initialTime - 1000);
        long oldTime = profile.getLastUsedAt();
        
        // Update should set a new timestamp
        profile.updateLastUsed();
        
        // The new time should be greater than the old time we set
        assertTrue(profile.getLastUsedAt() > oldTime);
    }

    @Test
    public void testDefaultPorts() {
        Profile profile = new Profile();
        
        // Should use default ports from AppKV constants
        assertEquals("8765", profile.getControlPort());
        assertEquals("5556", profile.getAdbPort());
    }

    @Test
    public void testProfileSetters() {
        Profile profile = new Profile();
        
        profile.setName("Custom Name");
        profile.setRootfsPath("/custom/path");
        profile.setControlPort("9999");
        profile.setAdbPort("5555");
        profile.setMode(Profile.MODE_SERVER);
        profile.setVerboseDebug(true);
        profile.setUse3rdPartyRom(true);
        
        assertEquals("Custom Name", profile.getName());
        assertEquals("/custom/path", profile.getRootfsPath());
        assertEquals("9999", profile.getControlPort());
        assertEquals("5555", profile.getAdbPort());
        assertEquals(Profile.MODE_SERVER, profile.getMode());
        assertTrue(profile.isVerboseDebug());
        assertTrue(profile.isUse3rdPartyRom());
    }

    @Test
    public void testToString() {
        Profile profile = new Profile("Test");
        profile.setMode(Profile.MODE_SERVER);
        profile.setRootfsPath("/path/to/rootfs");
        
        String toString = profile.toString();
        assertTrue(toString.contains("Test"));
        assertTrue(toString.contains(Profile.MODE_SERVER));
        assertTrue(toString.contains("/path/to/rootfs"));
    }

    @Test 
    public void testHashCode() {
        Profile profile1 = new Profile("Test1");
        Profile profile2 = new Profile("Test2");
        profile2.setId(profile1.getId());
        
        // Same ID should have same hash code
        assertEquals(profile1.hashCode(), profile2.hashCode());
    }
}
