// This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
// This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).

//! Standalone twoyi server binary
//! Execute directly: ./twoyi-server --help
//!
//! This binary shares the same code as the JNI library (libtwoyi.so) but runs
//! as a standalone CLI application instead of being called from Java.

// Import from the library crate
use twoyi::server;

use log::{info, error};

fn main() {
    // Initialize standard logging
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
    
    info!("twoyi-server starting...");
    
    // Collect command line arguments
    let args: Vec<String> = std::env::args().collect();

    // Run the server with command line arguments
    match server::run_server_cli(&args) {
        Ok(()) => {
            info!("Server exited successfully");
        }
        Err(e) => {
            error!("Server failed: {}", e);
            std::process::exit(1);
        }
    }
}
