// This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
// This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).

//! twoyi-server library
//!
//! This library provides the core server functionality for the twoyi container.
//! It can be used as:
//! - A JNI library called from the Android app (when built with `jni` feature)
//! - A standalone CLI binary (when built with `cli` feature)
//! - A Rust library for embedding

pub mod input;
pub mod framebuffer;
pub mod gralloc;
pub mod rom_patcher;
mod server;

// Re-export server functionality
pub use server::{ServerConfig, TwoyiServer};

// JNI bindings (only when jni feature is enabled)
#[cfg(feature = "jni")]
pub mod jni_bindings;
