// This file was generated by AI (GitHub Copilot) and is NOT APPLICABLE for copyright.
// This is part of the threetwi project, a fork of twoyi (https://github.com/twoyi/twoyi).

//! libtwoyi - twoyi container server library
//!
//! This library provides the core server functionality for the twoyi container.
//! It serves a dual purpose:
//! - As a JNI library called from the Android app (when loaded via System.loadLibrary)
//! - As a standalone executable (when run directly: ./libtwoyi.so -r rootfs)
//!
//! The library can be executed directly from Termux or command line.

pub mod input;
pub mod framebuffer;
pub mod gralloc;
pub mod rom_patcher;
mod server;
mod cli;

// Re-export server functionality
pub use server::{ServerConfig, TwoyiServer};

// JNI bindings (only when android feature is enabled)
#[cfg(feature = "android")]
pub mod jni_bindings;

/// Entry point when the library is executed directly (e.g., ./libtwoyi.so -r rootfs)
/// This is called via the _start symbol or when the linker treats the .so as executable
#[no_mangle]
pub extern "C" fn main(argc: libc::c_int, argv: *const *const libc::c_char) -> libc::c_int {
    cli::run_cli(argc, argv)
}
